# .github/workflows/pages.yml
name: Build and Deploy Jekyll to Pages

on:
  push:
    branches: [ master, dev ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read   # deploy-pages@v4 需要读取 Actions 权限

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Build site
        run: bundle exec jekyll build -d _site --trace
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
